### ISSUE TITLE
Geojson erroneous (very wide isochrone) with a French city

### ISSUE THREAD

**Issue by kofronpi** [route360/r360-js#25] opened 2016-06-14 13:39 UTC
Hello,

I'm thoroughly trying out your API to use the pro version in our project.

When requesting a 1800s isochrone in Rennes (lon:-1.681632::lat:48.113844), France with the geojson formatter the returned result is incorrect.

The request returns between 33 000 and 65 000 lines of geojson (randomly) - an isochrone including a sixth of France and most of the Atlantic Ocean.

Here's the request:

`https://service.route360.net/france/v1/polygon?cfg=%7B%22sources%22%3A%5B%7B%22lat%22%3A48.109784%2C%22lng%22%3A-1.679091%2C%22id%22%3A%22%22%2C%22tm%22%3A%7B%22car%22%3A%7B%7D%7D%7D%5D%2C%22elevation%22%3Atrue%2C%22polygon%22%3A%7B%22serializer%22%3A%22geojson%22%2C%22values%22%3A%5B1800%5D%7D%7D&key=YOUR_KEY`

In the result payload, the suspicious area:

```
    "properties": {
           "area": 1667162164.307389,
           "time": 1800
         }
```

A pic of the result imported into QGIS:
![bug_rennes_route360](https://cloud.githubusercontent.com/assets/5551692/16044725/e966c2f6-3245-11e6-8845-686bf85e475c.png)

**Comment by gerbsen** [comment] 2016-06-14 13:55
oh wow. that's probably not all reachable. :) we look into it! fyi the lat/lngs from the URL and Rennes are not identical. Which are the wrong ones? Does this also happen with the normal json result or only with geojson? 

@hollburg could you have a look

**Comment by kofronpi** [comment] 2016-06-14 14:16
Yes sorry, I experimented with a lot of different places and both of these return erroneous, too-wide isochrones. It apparently happen only with GeoJSON (I modified your codepen to try out Rennes and it was ok).

**Comment by hollburg** [comment] 2016-06-15 08:55
Ok. Thanks for pointing this out @kofronpi . The GeoJSON feature is very new and obviously hasn't been tested enough. I'll look into this asap.

**Comment by hollburg** [comment] 2016-06-16 08:45
I've wrote a fix for this issue yesterday. It will become effective with the next update. Probably next week,

**Comment by gerbsen** [comment] 2016-07-14 15:20
Duplicate of issue #23

**Closed by gerbsen** 2016-07-14 15:20 UTC
Labels: duplicate
